# Generated by Django 3.0.3 on 2020-02-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/home/amirhossein/DjangoPractice/projects/simpleblog/files/default.jpg', upload_to='profile_pics'),
        ),
    ]
